name: TechTrends - Package with Docker

# Trigger on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "package-and-push"
  package-and-push:
    # Run the action on the ubuntu-latest operating system
    runs-on: ubuntu-latest

    # referenced https://github.com/marketplace/actions/build-and-push-docker-images
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    # For the Docker build and push step:
    # Context should be set to the project directory
    # Reference the Dockerfile for TechTrends application
    # Push the image to DockerHub with the tag techtrends:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: millercm/techtrends:latest
